version: '3.8'
services:
  subconverter: 
    image: tindy2013/subconverter:latest
    hostname: subconverter
    container_name: subconverter
    volumes:
      - ./subconverter/all_base.tpl:/base/base/all_base.tpl
      - ./subconverter/pref.toml:/base/pref.toml
    ports:
      - "25500:25500"

  clash-with-ui:
    build: .
    container_name: clash-with-ui
    depends_on:
      - subconverter
    env_file:
      - .env
    ports:
      - "$ALL_PROXY_PORT:7890"
      - "$CONTROL_PANEL_PORT:9090"